### ISSUE TITLE
Getting InvalidParameterValueException while registering using Hook command

### ISSUE THREAD

**Issue by MaushamGupta** [awslabs/aws-lambda-fanout#19]
Hi All,

I am getting below error while using the hook command to register the event source mapping for cross Aws Account:

**An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: Role and event source must be in the same account as the cloud function.**

I have a kinesis stream in account A and I have a Lambda function in account B. I am trying to register the kinesis stream in account A to Lambda function in account B.

Your help will be really appreciated.

Thanks

**Comment by julienlepine** [comment]
Hello, attaching an AWS Lambda function to an Amazon Kinesis stream only works when the Kinesis stream and the Lambda are in the same account.

If you want to call functions in account B, you can hook the fan out function deployed in account A to your stream in account A, and ask it to call with a cross-account role a function in account B. Just create a target of type Lambda and specify a role in account B.

**Comment by MaushamGupta** [comment]
Hi julienlepine ,

Thanks for the reply that really helps. 

Can you please help me understand **" ask it to call with a cross-account role a function in account B. Just create a target of type Lambda and specify a role in account B."**
 I didn't get this statement.

Thanks
