### ISSUE TITLE
Unrecognized DynamoDB Stream arn

### ISSUE THREAD

**Issue by statelessness** [awslabs/aws-lambda-fanout#3]
Hi,

When configuring a mapping for a DynamoDB Stream, the lambda generates the following error:

_Invalid configuration for target 'target1' of type 'kinesis', 'sourceArn' property must be a valid ARN of an Amazon Kinesis Stream or Amazon DynamoDB Stream. Ignoring target_

I think that the problem is related to an erroneous regex in configuration.js file. Current value of regex is:

_var sourceRegex = /^arn:aws:((kinesis:[a-z]+-[a-z]+-[0-9]:[0-9]{12}:stream\/([a-zA-Z0-9_-]{1,128}))|(kinesis:[a-z]+-[a-z]+-[0-9]:[0-9]{12}:table\/[A-Za-z0-9_.-]\/stream\/[0-9A-Z_.:-]+))$/;_

I've replaced it with the following regex and it has worked:

_var sourceRegex = /^arn:aws:((kinesis:[a-z]+-[a-z]+-[0-9]:[0-9]{12}:stream\/([a-zA-Z0-9_-]{1,128}))|(dynamodb:[a-z]+-[a-z]+-[0-9]:[0-9]{12}:table\/[A-Za-z0-9_.-]+\/stream\/[0-9A-Z_.:-]+))$/;_

KR,

Juan Carlos González

**Comment by julienlepine** [comment]
Yes indeed, must have been a copy paste error in my last refactoring.

Fixed in master.
