### ISSUE TITLE
Incomplete DynamoDB records in Kinesis Stream

### ISSUE THREAD

**Issue by statelessness** [awslabs/aws-lambda-fanout#4]
Hi,

I've configured fanout Lambda for replicating DynamoDB Stream events to a Kinesis Stream. When I make changes to DynamoDb table, events appear in Kinesis Stream. However it looks like the events are not complete as some attributes are missing: eventName, sequenceNumber, etc. It looks like the only attributes available are those contained in NewImage attribute. 

KR,

Juan Carlos González

**Comment by julienlepine** [comment]
Sorry about that, yes, this is indeed the case. We could add a new target that would support this use case.
