### ISSUE TITLE
Buffer deprecation error 

### ISSUE THREAD

**Issue by yogeshkv** [awslabs/aws-lambda-fanout#44]
I am getting the below deprecation warning/error while running the code from AWS Lambda with Node.js 10.x runtime. Much appreciated for suggestions

ERROR	(node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by jerith666** [comment]
Looks like a58cdbe2fd5f624860bd05949577f38f206c6b02 is a fix for this.

**Comment by calcac** [comment]
Hi, Is there plan to update the master branch with this fix?
