### ISSUE TITLE
Destination role ARN not working for cross-account

### ISSUE THREAD

**Issue by toddrosner** [awslabs/aws-lambda-fanout#5]
I'm trying to setup a mapping that works with cross-account support. When I register the mapping and try to use the `--destination-role-arn`, the response is the following:

`Invalid ARN 'arn:aws:iam::012345678910:role/fanoutCrossAccountRole', must be a fully qualified AWS IAM Role ARN` 

The format I'm using for the register action is as follows:

```
./fanout register kinesis --function fanout --source-type kinesis --source source-stream --id target1 --destination arn:aws:kinesis:us-west-2:012345678910:stream/target-stream --destination-region us-west-2 --destination-role-arn arn:aws:iam::012345678910:role/fanoutCrossAccountRole --active true --profile redacted --region us-west-2
```

However, the following does work including the `--destination` ARN, but it does not provide cross-account support because it's missing the `--destination-role-arn`, and is really just to prove that the ARN format is correct:

```
./fanout register kinesis --function fanout --source-type kinesis --source source-stream --id target2 --destination arn:aws:kinesis:us-west-2:012345678910:stream/target-stream --destination-region us-west-2 --active true --profile redacted --region us-west-2
```

Is the `--destination-role-arn` feature for cross-account support functional? If so, what am I missing?

**Comment by toddrosner** [comment]
I see now that the conditional on line 248 of targets.sh is the following:

```
if [ ! -z "${DESTINATION_ROLE_ARN}" ]; then
    DESTINATION_ROLE_NAME=$( echo "$DESTINATION_ROLE_ARN" | sed -E -n 's#^arn:aws:iam::role/([a-zA-Z0-9+=,.@_-]{1,64})$#\1#p' )
    if [ -z "${DESTINATION_ROLE_NAME}" ]; then
      echo "Invalid ARN '${DESTINATION_ROLE_ARN}', must be a fully qualified AWS IAM Role ARN" 1>&2
      exit -1
    fi
fi
```

...when it looks like it should be the following:

```
if [ ! -z "${DESTINATION_ROLE_ARN}" ]; then
    DESTINATION_ROLE_NAME=$( echo "$DESTINATION_ROLE_ARN" | sed -E -n 's#^arn:aws:iam::[0-9]{12}:role/([a-zA-Z0-9+=,.@_-]{1,64})$#\1#p' )
    if [ -z "${DESTINATION_ROLE_NAME}" ]; then
      echo "Invalid ARN '${DESTINATION_ROLE_ARN}', must be a fully qualified AWS IAM Role ARN" 1>&2
      exit -1
    fi
fi
```

Note the `DESTINATION_ROLE_NAME` variable line and how it's missing the regex for the account number in the original.

With this update I no longer receive the message about the ARN not being fully qualified when registering the mapping, however, I also don't see any update to the DynamoDB table that suggests the destination role has been configured to be used.

**Comment by toddrosner** [comment]
Also discovered that line 83 of configuration.js is missing the regex for the account number, and this prevents any cross-account access.

`var roleRegex = /^arn:aws:iam::role\/([a-zA-Z0-9+=,.@_-]{1,64})$/;`
should be
`var roleRegex = /^arn:aws:iam::[0-9]{12}:role\/([a-zA-Z0-9+=,.@_-]{1,64})$/;`

Once this is updated, cross-account access works.

**Comment by toddrosner** [comment]
Lastly, I've discovered that the following should be updated for targets.sh so that the role and externalId properties can be properly added to DynamoDB when registering a target using the fanout command:
1. Line 185 should contain the following line:
   `EXTERNAL_ID=`
2. Starting at line 234 should be the following logic:

```
elif [ "$CODE" == "--external-id" ]; then
  if [ $# -ne 0 ]; then
    EXTERNAL_ID=$1
    shift
  else
    echo "readTargetParams: You must specify a value for parameter $CODE" 1>&2
    doHelp
    exit -1
fi
```
1. Lines 412 and 413 should be changed to:

```
if [ ! -z "${DESTINATION_ROLE_ARN}" ]; then
      appendJsonProperty "$1" "role" "{\"S\":\"${DESTINATION_ROLE_ARN}\"}"
```

**Comment by toddrosner** [comment]
I would create a pull request for this issue, but it appears the repo has push restrictions.

```
fatal: unable to access 'https://github.com/awslabs/aws-lambda-fanout.git/': The requested URL returned error: 403
```

**Comment by julienlepine** [comment]
PR accepted on this
