### ISSUE TITLE
TypeError when publishing from Kinesis to Redis

### ISSUE THREAD

**Issue by billsinc** [awslabs/aws-lambda-fanout#7]
When fetching from a Kinesis stream and pushing to Redis (AWS Elasticache), I get the following error in CloudWatch:

> Error occured while preparing Redis command: [TypeError: list argument must be an Array of Buffers.]

Not being familiar with Redis does some preparation need to be done before writing data?

**Comment by julienlepine** [comment]
I had not seen your issue before (GitHub configuration issue). Do you have any stack trace about this?

**Comment by julienlepine** [comment]
I think I have found the cause. Can you check again?
